### ISSUE TITLE
Multiple occurence on a same post

### ISSUE THREAD

**Issue by guillaumemolter** [theideabureau/acf-reusable-group-field#1]
Sadly I just realized that the reusable group doesn't work if you have more than one reusable group field on a same post.

How to reproduce:
- Create a group field (stats) that will be reused.
- Create 2 fields groups (section 1 & section 2) on the same post type (report).
- Add the first reusable group (stats) as a reusable group field to the 2 others (section 1 & section 2).
- Now create a post (report) and add content to section 1 and save. Content will be duplicated in section 2 and on the front end get_fields() will ignore section 1 & section 2 and will return stats.

I would love to find a fix for that. Does anyone has a clue and or an idea?

Using : WP 3.8.1 & ACF 4.3.4

**Comment by shanomurphy** [comment]
It kinda makes sense that the same field group can't have more than one instance on the same page as it is basically just a duplicate, and there is nothing to distinguish the first instance from the second instance.

I was hoping multiple instances would work within Flexible Content Fields and Repeater Fields (as the rows distinguish them) but unfortunately it doesn't seem to, and I'm experiencing the same problem as you are. See Issue https://github.com/theideabureau/acf-reusable-group-field/issues/2

**Comment by beneverard** [comment]
I don't think this is a bug, the same would happen if two standard fields with the same name existed in the same editor page too. 

I do think the exception is within repeatable ACF fields, see #2 for that issue.
