### ISSUE TITLE
Can't Have More Than One Instance Within Flexible Content or Repeater Fields

### ISSUE THREAD

**Issue by shanomurphy** [theideabureau/acf-reusable-group-field#2]
Reusable groups don't seem to work within repeater fields or Flexible content fields if you have more than one instance of the reusable group e.g. it gets used on more than one row.

**How to reproduce:**
1. Create a field group that you wish to reuse
2. Create a new field group that contains a Flexible Content field
3. Within the Flexible Content field use Reusable Group Field and select the field group from step one
4. Create a new post using the field group from step two
5. Add a row (that contains Reusable Group Field) and enter values in the field(s)
6. Add another row (that contains same Reusable Group Field)
7. The values will be a duplicate of the first row

_Using WP v3.8.1 & ACF v4.3.4_

**Comment by beneverard** [comment]
Hi @shanomurphy,

Yes I expect this is the case, when I created this plugin it was to fulfil a very basic requirement, so yes this is a valid issue right now.

I'm more than happy for someone to come along and fix this issue, I don't have time to make further changes at the moment.

**Comment by shanomurphy** [comment]
Hi Ben,

Yes I perfectly understand – I just thought I'd document it in case anyone else fancies tackling it.

Thanks for the plugin it has proved very useful so far! If I get some free time I'm going to have a play around at fixing this issue, though it will most likely be beyond me.

**Comment by amityweb** [comment]
Is this fixed?

**Comment by shanomurphy** [comment]
You don't need a plugin to reuse field groups or fields any more. ACF 5.4.0 added this functionality with the [Clone Field](https://www.advancedcustomfields.com/resources/clone/).

**Comment by amityweb** [comment]
Oh brilliant, I hadn't updated my plugin. The new field works great. Sorry to bother you.

**Comment by beneverard** [comment]
Yes good to see ACF now have this built in.
